### ISSUE TITLE
Google Play lib conflict

### ISSUE THREAD

**Issue by SquirrelMobile** [JosephAustin/ti.admobint#1]
Hello, thanks for your module and the interstitial support on Android.
But, i have a conflict with the pushwoosh module here : https://github.com/Pushwoosh/pushwoosh-appcelerator-titanium, i think they use the same library. The google-play-services-ads.jar is 1.3 mo, are you sure the ti.admob module need all the lib ? If not, can you split/remove the unused class to reduce the size and avoir conflict with other module please ?

This is my output log : 
```[ERROR] Failed to run dexer:
[ERROR]   
[ERROR] Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzas;
[ERROR] Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzat;
[ERROR] Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzlv;
[ERROR] Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzlw;
[ERROR] Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzlx;
[ERROR] Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzlx$zza;
[ERROR] Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzly;
[ERROR] Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzlz;
[ERROR] Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzme;
[ERROR]   
[ERROR] UNEXPECTED TOP-LEVEL EXCEPTION:
[ERROR] java.lang.RuntimeException: Translation has been interrupted
[ERROR]         at com.android.dx.command.dexer.Main.processAllFiles(Main.java:608)
[ERROR]         at com.android.dx.command.dexer.Main.runMultiDex(Main.java:366)
[ERROR]         at com.android.dx.command.dexer.Main.run(Main.java:275)
[ERROR]         at com.android.dx.command.dexer.Main.main(Main.java:245)
[ERROR]         at com.android.dx.command.Main.main(Main.java:106)
[ERROR] Caused by: java.lang.InterruptedException: Too many errors
[ERROR]         at com.android.dx.command.dexer.Main.processAllFiles(Main.java:600)
[ERROR]         ... 4 more```

**Comment by kerbooo** [comment]
Have you tried this solution? 
[https://www.youtube.com/watch?v=Coei6zvPIys](https://www.youtube.com/watch?v=Coei6zvPIys)

**Comment by JosephAustin** [comment]
Just now seeing this,  I'm sorry. Hmm, I didn't expect the libs to collide like that. Unfortunately when I built it, it wanted to be built with that library - even the appcelerator modules do that. I will give it a look.

**Comment by JosephAustin** [comment]
Definitely try Kerboo's thing, it looks like this is a common enough problem if someone made a video on it.

**Comment by SquirrelMobile** [comment]
Yes, it's ok now, thanks.
